language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  - PHPUNIT="vendor/bin/phpunit --verbose --coverage-clover=coverage.clover"

matrix:
  exclude:
    - php: nightly
      env: PHPUNIT="vendor/bin/phpunit --verbose --coverage-clover=coverage.clover"
  include:
    - php: nightly
      env: PHPUNIT="phpunit --verbose"
  allow_failures:
    - php: nightly
  fast_finish: true

# faster builds on new travis containers
sudo: false

install:
  - composer self-update && composer --version
  - composer install --prefer-dist

script:
  - $PHPUNIT
#  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
